javax:
  net:
    ssl:
      trustStore: ${TRUSTSTORE_PATH}
      trustStorePassword : ${TRUSTSTORE_PASSWORD}

opensearch:
  username: ${OPENSEARCH_USERNAME}
  password: ${OPENSEARCH_PASSWORD}
  host : ${OPENSEARCH_HOST}
  post : ${OPENSEARCH_PORT}
