javax:
  net:
    ssl:
      trustStore: ${TRUSTSTORE_PATH}
      trustStorePassword : ${TRUSTSTORE_PASSWORD}

opensearch:
  username: ${OPENSEARCH_USERNAME}
  password: ${OPENSEARCH_PASSWORD}
  host : ${OPENSEARCH_HOST}
  post : ${OPENSEARCH_PORT}

s3:
  bucket:
    name: ${S3_BUCKET_NAME}

spring:
  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      s3:
        bucket: ${S3_BUCKET_NAME}
      region:
        static: ap-northeast-2
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
